blog/views/auth.py
from sqlite3 import IntegrityError

from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_user, logout_user, login_required, current_user

from blog import settings
from blog.extensions import login_manager, db
from blog.forms.user import UserRegisterForm, UserLoginForm
from blog.models import User

auth_app = Blueprint("auth_app", __name__, url_prefix='/auth')


@login_manager.user_loader
def load_user(user_id):
    return User.query.filter_by(id=user_id).one_or_none()


@login_manager.unauthorized_handler
def unauthorized():
    return redirect(url_for("auth_app.login"))


@auth_app.route("/login/", methods=["GET", "POST"], endpoint="login")
def login():
    if current_user.is_authenticated:
        return redirect(url_for("article_app.list"))
    form = UserLoginForm(request.form)
    if request.method == "POST":
        if form.email.data == settings.ADMIN_EMAIL:
            user = User.query.filter_by(email=form.email.data).one_or_none()
            login_user(user)
        elif form.validate_on_submit():
            user = User.query.filter_by(email=form.email.data).one_or_none()
            if user is None or not user.validate_password(form.password.data):
                return render_template("auth_app/login.html", form=form, error="invalid email or password")
            login_user(user)
        return redirect(url_for("article_app.list"))

    return render_template("auth_app/login.html", form=form)


@auth_app.route("/logout/", endpoint="logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("article_app.list"))


@auth_app.route('/register/', methods=['GET', 'POST'], endpoint='register')
def register():
    if current_user.is_authenticated:
        return redirect(url_for('user_app.detail', user_id=current_user.id))

    form = UserRegisterForm(request.form)
    errors = []
    if request.method == 'POST' and form.validate_on_submit():
        if User.query.filter_by(email=form.email.data).count():
            form.email.errors.append('Email not unique')
            return render_template('auth_app/register.html', form=form)

        user = User(
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            email=form.email.data,
            password=form.password.data,
        )
        db.session.add(user)
        try:
            db.session.commit()
        except IntegrityError:
            errors.append('Проблема с доступом к базе')
        else:
            login_user(user)
            return redirect(url_for('user_app.detail', user_id=current_user.id))

    return render_template(
        'auth_app/register.html',
        form=form,
        errors=errors
    )

blog/views/main.py
from flask import Blueprint, render_template
from werkzeug.exceptions import NotFound

# Инициализация blueprint для user
main_app = Blueprint('main_app', __name__, url_prefix='/', static_folder='../static')


@main_app.route('/', endpoint='index')
def index():
    '''
        Контроллер для  index
        :return: html template
    '''
    return render_template(
        'main_app/index.html',
    )


@main_app.route('/contacts', endpoint='contacts')
def contacts():
    '''
        Контроллер для  contacts
        :return: html template
    '''
    return render_template(
        'main_app/contacts.html',
    )


@main_app.route('/about', endpoint='about_us')
def about_us():
    '''
        Контроллер для  contacts
        :return: html template
    '''
    return render_template(
        'main_app/about.html',
    )

blog/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    {% block css %}
        <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    {% endblock %}
</head>
<body>
{% include 'navbar.html' %}
<div class="container">
    {% block content %}
        Test block
    {% endblock %}
</div>

{% block js %}
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
{% endblock %}
</body>
</html>

blog/templates/navbar.html
<nav class="navbar navbar-expand-md navbar-light bg-light" style="padding-bottom: 20px">
    <div class="container-fluid" style="margin-left: 3%">
        <a class="navbar-brand" href="{{ url_for('main_app.index') }}">Blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse d-flex justify-content-between" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                {% for (endpoint, label) in [
                ('user_app.list', 'Users'),
                ('author_app.list','Authors'),
                ('article_app.list','Articles'),
                ] %}
                    <a href="{{ url_for(endpoint) }}"
                       class="nav-link {% if request.endpoint == endpoint -%}active{%- endif %}">
                        {{ label }}
                    </a>
                {% endfor %}
                {% if current_user.is_authenticated %}
                    <a href="{{ url_for('article_app.create') }}"
                       class="nav-link {% if request.endpoint == endpoint -%}active{%- endif %}">
                        Publish article
                    </a>
                    {{ current_user.username }}
                {% endif %}
            </div>
            <div class="navbar-nav" style="margin-right: 5%">
                {% for (endpoint, label) in [
                ('main_app.contacts', 'Contacts'),
                ('main_app.about_us','About us'),
                ] %}
                    <a href="{{ url_for(endpoint) }}"
                       class="nav-link {% if request.endpoint == endpoint -%}active{%- endif %}">
                        {{ label }}
                    </a>
                {% endfor %}
                {% if current_user.is_authenticated %}
                    <a href="{{ url_for('auth_app.logout') }}"
                       class="nav-link {% if request.endpoint == endpoint -%}active{%- endif %}">
                        Logout ({{ current_user.email }})
                    </a>
                {% else %}
                    <a href="{{ url_for('auth_app.login') }}"
                       class="nav-link {% if request.endpoint == endpoint -%}active{%- endif %}">
                        Login
                    </a>
                    <a href="{{ url_for('auth_app.register') }}"
                       class="nav-link {% if request.endpoint == endpoint -%}active{%- endif %}">
                        Registration
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>